apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ability-cinema.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ability-cinema.name" . }}
    helm.sh/chart: {{ include "ability-cinema.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  configuration-file: |
    server.port: {{ .Values.containerPort }}
    server.log-level: {{ .Values.logLevel }}

    tools.allocine:
      host: "tool-allocine"
      port: 5555
